  # This playbook demonstrates logging in with different AWS roles and accessing EKS, EC2 and Load Balncers#
  # Important: Replace placeholders with your actual values#

  - Ansible installed on your local machine
- Ansible EC2 module ( boto3 library )
- Ansible EKS MODULE ( aws_eks library)
- Ansible ELBv2 module ( aws_lbv2 )

   [ eks_cluster]
   <eks_master_ip>  ansible_user=ec2-user

   [ ec2_instances]
   < ec2_private_ip_1 > ansible_user=ec2-user
   < ec2_private_ip_2 > ansible_user=ec2-user
